# Copyright parq.chat(TM). Licensed under AGPL 3. See https://github.com/parqchat/parqchat

package(default_visibility = ["//visibility:public"])

java_library(
  name = "util",
  srcs = glob(["*.java"]),
)
