# Copyright parq.chat(TM). Licensed under AGPL 3. See https://github.com/parqchat/parqchat

package(default_visibility = ["//visibility:public"])

filegroup(
  name = "ajs_mocks",
  srcs = ["ajs_mocks.js"],
  data = [
    "//webclient/main/js",
  ],
)
