# Copyright parq.chat(TM). Licensed under AGPL 3. See https://github.com/parqchat/parqchat

java_test(
  name = "DummyTest",
  srcs = ["DummyTest.java"],
  deps = [
    "//java/chat/parq/server"
  ]
)

